{{- if .Values.extraSecretFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.concatSecretName" . }}
type: Opaque
data:
  secrets.enc.yaml: |
    {{ .Values.extraSecretFile | b64enc | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.concatDecryptedSecretName" . }}
type: Opaque
data:
  x: {{ "placeholder" | b64enc }}
{{- end }}
